### GET ALL Products
# Retrieves all products from the database.
GET http://localhost:3000/api/product HTTP/1.1
Accept: application/json

### GET ONE Product
# Retrieves a single product by its ID.
GET http://localhost:3000/api/product/67609d58c716dfbf7ecfb6c5 HTTP/1.1
Accept: application/json

### CREATE ONE Product
# Adds a new product to the database.
POST http://localhost:3000/api/product HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "productId": "3150",
   "productName": "Camiseta de One Piece manga corta marfil para hombre",
   "price": 84900,
   "brand": "ONE PIECE",
   "linkText": "camiseta-hombre-exterior-one-piece-238249",
   "releaseDate": "2024-11-15T00:00:00Z",
   "categories": ["/Hombre/Camisetas/", "/Hombre/"],
   "link": "https://moviesshopco.vtexcommercestable.com.br/camiseta-hombre-exterior-one-piece-238249/p",
   "País de fabricación": [
      "Colombia \r\n- FABRICANTE/IMPORTADOR: Maquila Internacional de confección"
   ],
   "Registro Sic": ["811007991-8"],
   "Composición": [
      "Componente: Camiseta , Composición: 99% Algodón, 1% Elastano"
   ],
   "Especificaciones": [
      "- Camiseta cuello redondo, manga corta\r\n -tela algodón para mayor frescura y suavidad, cuello en rib para mayor comodidad -cuello con elongación para facilitar el paso de la cabeza\r\n- Regular fit\r\n- Estampado en relieve"
   ],
   "Color": ["Marfil"],
   "Cuidado": [
      "- Lavar a mano o en máquina \r\n- No lavar en seco \r\n- No dejar en remojo \r\n- No retorcer ni exprimir \r\n- Usar agua fría \r\n- Usar jabón suave \r\n- No usar blanqueador \r\n- No blanquear \r\n- No usar secadora \r\n- No planchar \r\n- Secado en tendedero a la sombra\r\n- No retorcer"
   ],
   "Categoría": ["Camisetas"],
   "Género": ["Hombre"],
   "items": [
      {
         "images": [
            {
               "imageId": "177739",
               "imageLabel": "",
               "imageTag": "<img src=\"~/arquivos/ids/177739-#width#-#height#/238249-camiseta-hombre-one-piece-camiseta-iconica-1.jpg?v=638664382146500000\" width=\"#width#\" height=\"#height#\" alt=\"238249-camiseta-hombre-one-piece-camiseta-iconica-1\" id=\"\" />",
               "imageUrl": "https://moviesshopco.vteximg.com.br/arquivos/ids/177739/238249-camiseta-hombre-one-piece-camiseta-iconica-1.jpg?v=638664382146500000",
               "imageText": "238249-camiseta-hombre-one-piece-camiseta-iconica-1",
               "imageLastModified": "2024-11-05T21:16:54.6500000Z"
            },
            {
               "imageId": "177740",
               "imageLabel": "",
               "imageTag": "<img src=\"~/arquivos/ids/177740-#width#-#height#/238249-camiseta-hombre-one-piece-camiseta-iconica-2.jpg?v=638664382275230000\" width=\"#width#\" height=\"#height#\" alt=\"238249-camiseta-hombre-one-piece-camiseta-iconica-2\" id=\"\" />",
               "imageUrl": "https://moviesshopco.vteximg.com.br/arquivos/ids/177740/238249-camiseta-hombre-one-piece-camiseta-iconica-2.jpg?v=638664382275230000",
               "imageText": "238249-camiseta-hombre-one-piece-camiseta-iconica-2",
               "imageLastModified": "2024-11-05T21:17:07.5230000Z"
            },
            {
               "imageId": "177741",
               "imageLabel": "",
               "imageTag": "<img src=\"~/arquivos/ids/177741-#width#-#height#/238249-camiseta-hombre-one-piece-camiseta-iconica-3.jpg?v=638664382390130000\" width=\"#width#\" height=\"#height#\" alt=\"238249-camiseta-hombre-one-piece-camiseta-iconica-3\" id=\"\" />",
               "imageUrl": "https://moviesshopco.vteximg.com.br/arquivos/ids/177741/238249-camiseta-hombre-one-piece-camiseta-iconica-3.jpg?v=638664382390130000",
               "imageText": "238249-camiseta-hombre-one-piece-camiseta-iconica-3",
               "imageLastModified": "2024-11-05T21:17:19.0130000Z"
            },
            {
               "imageId": "177742",
               "imageLabel": "",
               "imageTag": "<img src=\"~/arquivos/ids/177742-#width#-#height#/238249-camiseta-hombre-one-piece-camiseta-iconica-4.jpg?v=638664382613130000\" width=\"#width#\" height=\"#height#\" alt=\"238249-camiseta-hombre-one-piece-camiseta-iconica-4\" id=\"\" />",
               "imageUrl": "https://moviesshopco.vteximg.com.br/arquivos/ids/177742/238249-camiseta-hombre-one-piece-camiseta-iconica-4.jpg?v=638664382613130000",
               "imageText": "238249-camiseta-hombre-one-piece-camiseta-iconica-4",
               "imageLastModified": "2024-11-05T21:17:41.3130000Z"
            }
         ]
      }
   ],
   "skuSpecifications": [
      {
         "values": [
            {
               "id": "56",
               "name": "XS",
               "position": 1,
               "quantity": 1
            },
            {
               "id": "57",
               "name": "S",
               "position": 2,
               "quantity": 3
            },
            {
               "id": "58",
               "name": "M",
               "position": 3,
               "quantity": 0
            },
            {
               "id": "59",
               "name": "L",
               "position": 4,
               "quantity": 5
            },
            {
               "id": "60",
               "name": "XL",
               "position": 5,
               "quantity": 3
            }
         ]
      }
   ]
}

### UPDATE ONE Product
# Updates an existing product by ID.
PUT http://localhost:3000/api/product/67609d58c716dfbf7ecfb6c5 HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   "productId": "3089",
   "productName": "Camiseta de Snoopy manga corta azul para mujer",
   "price": 84900,
   "brand": "SNOOPY",
   "linkText": "camiseta-mujer-exterior-snoopy-238095",
   "releaseDate": "2024-08-15T00:00:00Z",
   "categories": ["/Mujer/Camisetas/", "/Mujer/"],
   "link": "https://moviesshopco.vtexcommercestable.com.br/camiseta-mujer-exterior-snoopy-238095/p",
   "País de fabricación": [
      "Colombia \r\n- FABRICANTE/IMPORTADOR: Maquila Internacional de confección"
   ],
   "Registro Sic": ["811007991-8"],
   "Composición": ["99% Algodón   1% Elastano"],
   "Especificaciones": [
      "- Regular fit \r\n- Camiseta cuello redondo, manga corta\r\n -tela algodón para mayor frescura y suavidad -cuello con elongación para facilitar el paso de la cabeza"
   ],
   "Color": ["Azul"],
   "Cuidado": [
      "- Lavar a mano o en máquina \r\n- No lavar en seco \r\n- No dejar en remojo \r\n- No retorcer ni exprimir \r\n- Usar agua fría \r\n- Usar jabón suave \r\n- No usar blanqueador \r\n- No blanquear \r\n- No usar secadora \r\n- No planchar \r\n- Secado en tendedero a la sombra"
   ],
   "Categoría": ["Camisetas"],
   "Género": ["Mujer"],
   "items": [
      {
         "images": [
            {
               "imageId": "177319",
               "imageLabel": "",
               "imageTag": "<img src=\"~/arquivos/ids/177319-#width#-#height#/238095-camiseta-mujer-snoopy-manga-corta-1.jpg?v=638585563734470000\" width=\"#width#\" height=\"#height#\" alt=\"238095-camiseta-mujer-snoopy-manga-corta-1\" id=\"\" />",
               "imageUrl": "https://moviesshopco.vteximg.com.br/arquivos/ids/177319/238095-camiseta-mujer-snoopy-manga-corta-1.jpg?v=638585563734470000",
               "imageText": "238095-camiseta-mujer-snoopy-manga-corta-1",
               "imageLastModified": "2024-08-06T15:52:53.4470000Z"
            },
            {
               "imageId": "177320",
               "imageLabel": "",
               "imageTag": "<img src=\"~/arquivos/ids/177320-#width#-#height#/238095-camiseta-mujer-snoopy-manga-corta-2.jpg?v=638585563844130000\" width=\"#width#\" height=\"#height#\" alt=\"238095-camiseta-mujer-snoopy-manga-corta-2\" id=\"\" />",
               "imageUrl": "https://moviesshopco.vteximg.com.br/arquivos/ids/177320/238095-camiseta-mujer-snoopy-manga-corta-2.jpg?v=638585563844130000",
               "imageText": "238095-camiseta-mujer-snoopy-manga-corta-2",
               "imageLastModified": "2024-08-06T15:53:04.4130000Z"
            },
            {
               "imageId": "177321",
               "imageLabel": "",
               "imageTag": "<img src=\"~/arquivos/ids/177321-#width#-#height#/238095-camiseta-mujer-snoopy-manga-corta-3.jpg?v=638585563931870000\" width=\"#width#\" height=\"#height#\" alt=\"238095-camiseta-mujer-snoopy-manga-corta-3\" id=\"\" />",
               "imageUrl": "https://moviesshopco.vteximg.com.br/arquivos/ids/177321/238095-camiseta-mujer-snoopy-manga-corta-3.jpg?v=638585563931870000",
               "imageText": "238095-camiseta-mujer-snoopy-manga-corta-3",
               "imageLastModified": "2024-08-06T15:53:13.1870000Z"
            },
            {
               "imageId": "177322",
               "imageLabel": "",
               "imageTag": "<img src=\"~/arquivos/ids/177322-#width#-#height#/238095-camiseta-mujer-snoopy-manga-corta-.jpg?v=638585564025570000\" width=\"#width#\" height=\"#height#\" alt=\"238095-camiseta-mujer-snoopy-manga-corta-\" id=\"\" />",
               "imageUrl": "https://moviesshopco.vteximg.com.br/arquivos/ids/177322/238095-camiseta-mujer-snoopy-manga-corta-.jpg?v=638585564025570000",
               "imageText": "238095-camiseta-mujer-snoopy-manga-corta-",
               "imageLastModified": "2024-08-06T15:53:22.5570000Z"
            }
         ]
      }
   ],
   "skuSpecifications": [
      {
         "values": [
            {
               "id": "56",
               "name": "XS",
               "position": 1,
               "quantity": 0
            },
            {
               "id": "57",
               "name": "S",
               "position": 2,
               "quantity": 2
            },
            {
               "id": "58",
               "name": "M",
               "position": 3,
               "quantity": 2
            },
            {
               "id": "59",
               "name": "L",
               "position": 4,
               "quantity": 0
            }
         ]
      }
   ]
}

### DELETE ONE Product
# Deletes a product by its ID.
DELETE http://localhost:3000/api/product/67609d58c716dfbf7ecfb6c5 HTTP/1.1
Accept: application/json
