
###
GET http://localhost:3000/api/product HTTP/1.1


###
GET http://localhost:3000/api/product/6753b62cd6cdf3b729a8d0b2 HTTP/1.1


###
POST http://localhost:3000/api/product HTTP/1.1
Content-Type: application/json

{
   "name": "Prueba 1",
   "description": "Lorem ipsum dolor",
   "linkId": "camiseta-mujer-movies--225390",
   "releaseDate": "2024-12-06 00:00"
}


###
PUT http://localhost:3000/api/product/6753b62cd6cdf3b729a8d0b2 HTTP/1.1
Content-Type: application/json

{
   "name": "Prueba 1",
   "description": "Lorem ipsum dolor sit amet",
   "linkId": "camiseta-mujer-movies--225389",
   "releaseDate": "2024-12-06 00:00"
}


###
DELETE http://localhost:3000/api/product/6753b62cd6cdf3b729a8d0b2 HTTP/1.1
